# Generated by Django 4.1.7 on 2023-06-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('clave_producto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('categoria_producto', models.CharField(blank=True, max_length=50)),
                ('catidad_producto', models.IntegerField(max_length=20)),
                ('catidad_reserva_producto', models.IntegerField(max_length=20)),
                ('precio_compra_producto', models.IntegerField(max_length=20)),
                ('precio_venta_producto', models.IntegerField(max_length=20)),
                ('fecha_caducidad_producto', models.DateField(null=True)),
                ('informacion_producto', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
