# Generated by Django 4.1.7 on 2023-06-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='catidad_producto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='catidad_reserva_producto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_compra_producto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_venta_producto',
            field=models.IntegerField(),
        ),
    ]
