# Generated by Django 4.1.7 on 2023-06-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categorias_alter_productos_catidad_producto_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productos',
            table='citas',
        ),
    ]
