# Generated by Django 4.1.7 on 2023-06-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_productos_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
    ]
