# Generated by Django 4.1.7 on 2023-06-13 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_productos_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorias',
            table='categorias',
        ),
    ]
